### PR TITLE
Color update: icon/default and text/alternative

### PR DESCRIPTION
**Pull request by georgewrmarshall**
### Description
Updating colors:
Light theme icon/default from: grey500: #6A737D => grey800: #24272A
Dark theme icon/default from: grey040: #F2F4F6 => white000: #FFFFFF
Dark theme text/alternative from: grey030: #FAFBFC => grey100: #D6D9DC

### design tokens storybook
Screen Shot 2022-04-08 at 11 51 16 AM
Screen Shot 2022-04-08 at 12 06 33 PM
Screen Shot 2022-04-08 at 11 51 38 AM

### Testing in extension
Screen Shot 2022-04-08 at 12 10 02 PM
Screen Shot 2022-04-08 at 12 16 31 PM
Screen Shot 2022-04-08 at 12 22 52 PM

Fixes: https://github.com/MetaMask/design-tokens/issues/74
Fixes: https://github.com/MetaMask/design-tokens/issues/83

### CODE REVIEW

**Comment by Akatori-Design** [comment]
Those example screenshots really helps. I think it looks good and consistent between color modes.

**Review by Akatori-Design — APPROVED** [review]
All three updates look correct.

**Comment by georgewrmarshall** [comment]
@Akatori-Design can you check all the values in the files are correct and approve 🙏

**Review by Cal-L — APPROVED** [review]
LGTM

**Pull request merged**
